#!/usr/bin/python

import sys

# A1 Basic Crypto

# 1. split cypher string into individual characters
# 2. for each letter in the alphabet, shift cypher over by the key amount
# 3. print shifted cyphers

cypher_string = "GBSXUCGSZQGKGSQPKQKGLSKASPCGBGBKGUKGCEUKUZKGGBSQEICACGKGCEUERWKLKUPKQQGCIICUAEUVSHQKGCEUPCBGCGQOEVSHUNSUGKUZCGQSNLSHEHIEEDCUOGEPKHZGBSNKCUGSUKUASERLSKASCUGBSLKACRCACUZSSZEUSBEXHKRGSHWKLKUSQSKCHQTXKZHEUQBKZAENNSUASZFENFCUOCUEKBXGBSWKLKUSQSKNFKQQKZEHGEGBSXUCGSZQGKGSQKUZBCQAEIISKOXSZSICVSHSZGEGBSQSAHSGKHMERQGKGSKREHNKIHSLIMGEKHSASUGKNSHCAKUNSQQKOSPBCISGBCQHSLIMQGKGSZGBKGCGQSSNSZXQSISQQGEAEUGCUXSGBSSJCQGCUOZCLIENKGCAUSOEGCKGCEUQCGAEUGKCUSZUEBGHSKGEHBCUGERPKHEHKHNSZKGGKAD"

alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"


# Helper methods
def split(word):
    return list(word)


def shift_cypher(cypher, shift):
    print(cypher_string)


# Main method
def main():
    shift_cypher(cypher_string, 1)


if __name__ == "__main__":
    main()